### ISSUE TITLE
Provide binary distribution

### ISSUE THREAD

**Issue by falzm** [mminer/scratchpad#4]
Hi

Could you please provide a compiled binary of your application? Not everyone has/wants Xcode installed or know how to use it 😏

**Comment by mminer** [comment]
Sorry, I’m no longer maintaining this repo (as you may have guessed 😬). As I note in the README, you might want to check out [Tyke](https://tyke.app/) or [Tot](https://tot.rocks/) if you want a simple scratchpad for macOS.
